on:
  push:
    branches: [main, master, dev, ci]
  pull_request:
    branches: [main, master]

name: CI-checks

jobs:
  CI-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
            java-version: 11.0.4

      - name: Install Nextflow
        run: curl -fsSL get.nextflow.io | bash && mv nextflow /usr/local/bin

      - name: Install spiff
        run: git clone https://github.com/dontcallmedom/spiff && make -C spiff && mv spiff/spiff /usr/local/bin

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Run CI checks
        run: ./ci/ci.sh run && ./ci/ci.sh validate 
        
